### ISSUE TITLE
Inquiry about security

### ISSUE THREAD

**Issue by rikako3** [safing/portmaster-windows-kext#32]
Hi, first of all, thank you for creating Portmaster. It's a very useful application and I'm glad you decided to offer it as FOSS.

I wanted to ask about the security of the kernel extension. I'm not an expert at all, but it seems a bit scary to me that privileged C code is analyzing untrusted input (internet traffic). I see that you use static analysis. Apart from that, have you considered fuzzing to find potential vulnerabilities or other measures to prevent exploitation?

**Comment by vlabo** [comment]
That is a good point. We haven't considered it at the moment.

Since we are using exclusively Windows api for working with the network packets and portmaster is only concern with the meta data of the packets the attack surface is really small and if there is a vulnerability its more likely to be in the windows library which has been around for long time.

The part that we could test with fuzzing is with the communication with the core service. Which requires admin privileges to use or exploit.

We have planned a complete rewrite of the kernel extension which will provide more stability and security.
